### ISSUE TITLE
Access to treatment response data

### ISSUE THREAD

**Issue by guillaumejaume** [CBIIT/lgcp#1]
Hi, 

Thanks for this amazing resource. I couldn't find the treatment response status on the Biopsy-Clinical-Data file. I was wondering if the data is public, or it requires additional approval?

Thanks!

**Comment by bc2zb** [comment]
Can you specify which files you are trying to use so I can tag the appropriate contributer.

**Comment by guillaumejaume** [comment]
Thanks for the prompt answer! I'd like to access the neoadjuvant therapy response linked to the histopathology slides accessible here: https://www.cancerimagingarchive.net/collection/nadt-prostate/. I couldn't find this information in the metadata file associated with the cohort (https://www.cancerimagingarchive.net/wp-content/uploads/Biopsy-Clinical-Data.xlsx).

**Comment by guillaumejaume** [comment]
Found it, thanks!
